download_url: https://galaxy.ansible.com/download/community-kubevirt-1.0.0.tar.gz
format_version: 1.0.0
name: kubevirt
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.0.0
version_url: https://galaxy.ansible.com/api/v2/collections/community/kubevirt/versions/1.0.0/
