- name: Create VM in Openshift using community kubvirt modules
  hosts: localhost
  vars:
    vm_name: kubevirt-vm1
    oc_namespace: default

  tasks:
  - name: create virtual machine using kubvirt ansible module
    community.kubevirt.kubevirt_vm:
      state: running
      name: "{{ vm_name }}"
      namespace: "{{ oc_namespace }}"
      cpu_cores: 2
      memory: 512Mi
      disks:
        - name: containerdisk
          volume:
            containerDisk:
              image: kubevirt/cirros-container-disk-demo:latest
          disk:
            bus: virtio

