- name: Create openshift object
  hosts: localhost
  #become: true
  vars:
    vm_name: ansible-test-vm
    oc_namespace: default

  tasks:


  - name: create kubernetes object from jinja2
    kubernetes.core.k8s:
      #kubeconfig: /home/bastion/ansible/kubeconfig-noingress
      state: present
      definition: "{{ lookup('template', item ) | from_yaml }}"
    loop:
    - virtual-machine.j2

